<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="get">
        <input type="text" name="number" placeholder="Enter A Number">
        <input type="submit" name="submit" value="Submit">
    </form>
    

   <?php
   if(isset($_REQUEST["submit"])){
    $my number = $_REQUEST["number"];


    function checkPrime($number)
    if($number == 0){
        return "Never inpu footikar
        "
    }
   }
   
   ?>
</body>
</html>