<?php 
$fruits=["orange1","Orange2","Mango1","mango2","apple"];
sort($fruits,SORT_NATURAL|SORT_FLAG_CASE);
echo "<pre>";
print_r($fruits);
echo "<pre>";
$number=[2,4,5,10,15,20,25,30,15,30];
rsort($number);
print_r($number);
$store="";
echo implode($store,$number);
echo "<br>";
$string=["a"=>"Mango","b"=>"banana","c"=>"jackfruit","d"=>"Orange"];
rsort($string,SORT_NATURAL|SORT_FLAG_CASE);
print_r($string);
$letters=["aab","ecdeb","dbced","bce"];
sort($letters);
print_r($letters);
echo "<pre>";
$string=["a"=>"Mango","b"=>"banana","c"=>"jackfruit","d"=>"Orange","A"=>"Apple"];
asort($string);
print_r($string);
echo "<hr>";
$array=["img12.png","img1.png","img2.png","img4.png","img8.png"];
sort($array);
print_r($array);
echo"<hr>";
natsort($array);
print_r($array);
echo "<hr>";
$array=array("Img8.png","img2.png","Img7.png","img.13.png");
natsort($array);
print_r($array);
echo "<hr>";
$array=array("Img8.png","img2.png","Img7.png","img13.png");
natcasesort($array);
print_r($array);
echo "<hr>";
$fruits=["b"=>"Manglo","d"=>"Orange","e"=>"Banana","f"=>"Apple"];
arsort($fruits);
print_r($fruits);
echo "<hr>";
$fruits=["b"=>"Manglo","a"=>"Orange","c"=>"Banana","f"=>"Apple","g"=>"Jackfruit"];
ksort($fruits);
print_r($fruits);
echo "<hr>";
$names=array("b"=>"Mamun","e"=>"Abdul","a"=>"karim","d"=>"Nadia","f"=>"jabbar");
krsort($names);
print_r($names);
?>